# Generated by Django 4.2.1 on 2023-05-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductCategory', models.CharField(max_length=100)),
                ('ProductPrice', models.IntegerField()),
                ('ProductImages', models.ImageField(upload_to='')),
            ],
        ),
    ]
